# Configurações do Servidor
server.port=8080

# Conexão com o Banco do Render
spring.datasource.url=jdbc:postgresql://dpg-d9fc5avavr4c73bucm5g-a.virginia-postgres.render.com:5432/todolist_nvnl?sslmode=require
spring.datasource.username=todolist_user
spring.datasource.password=gtq9AYk8NHLcwlMJlcakOJLQcsQB0Owv
# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true