# ==========================================
# CONFIGURAÇÃO DE SERVIDOR
# ==========================================
server.port=${PORT:8080}

# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (PostgreSQL)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d9fc5avavr4c73bucm5g-a.virginia-postgres.render.com/todolist_nvnl}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:todolist_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gtq9AYk8NHLcwlMJlcakOJLQcsQB0Owv}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURAÇÕES DO SWAGGER / SPRINGDOC OPENAPI
# ==========================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true